name: Secure Download RPM Packages
on:
  workflow_dispatch:

jobs:
  get-rpms:
    runs-on: ubuntu-latest
    steps:
      - name: Download Real RPM Files
        run: |
          mkdir -p my_rpms
          cd my_rpms
          
          # 使用小写 -o 强行指定本地保存的绝对文件名，彻底解决命名失败的 exit code 23 错误
          curl -L "https://aliyun.com" -o libnetfilter_cthelper-1.0.0-11.el7.x86_64.rpm
          curl -L "https://aliyun.com" -o conntrack-tools-1.4.4-7.el7.x86_64.rpm
          
          # 列出文件，以便你在 Actions 执行日志中直观地看到文件大小
          ls -lh
          
      - name: Pack and Upload
        uses: actions/upload-artifact@v4
        with:
          name: conntrack-rpm-bundle
          path: my_rpms/
